- src/rust-crypto/aesni.rs
- src/rust-crypto/cryptoutil.rs
`cargo test` gives with these changes.
test result: ok. 78 passed; 0 failed; 49 ignored; 0 measured
Please see also:
http://doc.rust-lang.org/std/primitive.slice.html#method.get_unchecked_mut
> rename unsafe_mut to get_unchecked_mut - fixes #196

- src/rust-crypto/aessafe.rs
A few small cleanups and some optimizations to Aessafe.
Before:
```
test aes::bench::aes_safe_bench                   ... bench:       899 ns/iter (+/- 118) = 17 MB/s
test aes::bench::aes_safe_x8_bench                ... bench:      2146 ns/iter (+/- 219) = 59 MB/s
```
After:
```
test aes::bench::aes_safe_bench                   ... bench:       836 ns/iter (+/- 17) = 19 MB/s
test aes::bench::aes_safe_x8_bench                ... bench:      1016 ns/iter (+/- 77) = 125 MB/s
```
> Improvements and optimizations to Aessafe

- src/rust-crypto/cryptoutil.rs
`Unsigned` -> `UnsignedInt`
closes #206
> Update to rust master

- src/rust-crypto/blockmodes.rs
- src/rust-crypto/cryptoutil.rs
- src/rust-crypto/md5.rs
- src/rust-crypto/ripemd160.rs
- src/rust-crypto/sha1.rs
- src/rust-crypto/sha2.rs
Note: This fixes all the syntax errors caused by the closure changes, and `cargo build` successfully builds the crate, but running `cargo test` causes rustc to die with an llvm error on both my machines.
> Fix breakage caused by the changes to closures in rust nightly

- src/rust-crypto/blockmodes.rs
Using FnMut trait objects seems to result in crashes when trying to run the tests.
> Change to using unboxed closures for the run_inc() test method in blockmodes.rs

- src/rust-crypto/blockmodes.rs
- src/rust-crypto/cryptoutil.rs
- src/rust-crypto/md5.rs
- src/rust-crypto/ripemd160.rs
- src/rust-crypto/sha1.rs
- src/rust-crypto/sha2.rs
Use unboxed closures everywhere that closures are used. This basically just effects symmetric cipher blockmode tests and the digests. The digests seem to see a very minor performance improvement:
before:
```
test sha1::bench::sha1_10                         ... bench:        48 ns/iter (+/- 1) = 208 MB/s
test sha1::bench::sha1_1k                         ... bench:      3986 ns/iter (+/- 375) = 256 MB/s
test sha1::bench::sha1_64k                        ... bench:    253095 ns/iter (+/- 2086) = 258 MB/s
```
after:
```
test sha1::bench::sha1_10                         ... bench:        46 ns/iter (+/- 0) = 217 MB/s
test sha1::bench::sha1_1k                         ... bench:      3924 ns/iter (+/- 41) = 260 MB/s
test sha1::bench::sha1_64k                        ... bench:    250463 ns/iter …
```
> Use unboxed closures everywhere

- src/curve25519.rs
Fixes a "the type of this value must be known in this context" compiler error.
> Add annotation to make variable type unambiguous

- src/hkdf.rs
- src/lib.rs
Implementation based off the pbkdf2 code, except this is fast, and not
for password hashing.
> Add support for HKDF (RFC 5869).

- src/salsa20.rs
The performance optimizations come mostly from processing a block at a time in the common case (same as my 'chacha20_perf' branch).
The cleanups aim to increase readability/maintainability of the code (storing the state as an array of 'u32's is more natural and how the papers are written), and also results in a fairly minor performance increase.
Before: salsa20::bench::salsa20_64k 403337 ns/iter (+/- 3252) = 162 MB/s
After: salsa20::bench::salsa20_64k 288177 ns/iter (+/- 1947) = 227 MB/s
> Salsa20 cleanups/performance optimizations.

- src/chacha20.rs
- src/cryptoutil.rs
- src/salsa20.rs
The log mostly describes this.  I didn't change the block cipher code, though the CTRx8 implementation should get a decent boost out of something like this.  If you would rather have a 64 bit targeted version, I can do that too, though the gains aren't massive.
The new utility routine does exactly what it says on the tin, except
that it processes 4 bytes at a time (and then handles the remainder if
any).
Before: chacha20::bench::chacha20_64k ... bench: 249568 ns/iter (+/- 24243) = 262 MB/s
After: chacha20::bench::chacha20_64k ... bench: 200760 ns/iter (+/- 4004) = 326 MB/s
It's worth noting that this could be even faster depending on the
target hardware eg:
* 64 bit -> Process 8 bytes at a time (~350 MiB/s).
* 64 bit, allows unaligned memory access -> transmute() (~370 MiB/s).
But, ARM …
> Add cryptoutil::xor_keystream().

- src/salsa20.rs
The salsa20 code breaks (SIGSEGV, illegal hardware instruction) when linked from another crate with the latest nightly, the first change fixes that.  Not sure why the unit tests pass, and code from another crate breaks, but this fixes it.  Sorry about that.
The 2nd change because one-shot HChaCha20 is needed for NaCl's box construct (I have the rust-crypto crate mostly done, but not checked in yet).
> Salsa20 fixes

- src/sha1.rs
- src/sha2.rs
First, some background. Both ARM and Intel are releasing documentation that they plan to include instruction set extensions for SHA1 and SHA256 sometime in the near future. Intel has [some documentation](https://software.intel.com/en-us/articles/intel-sha-extensions) about it, and I wrote [a blog entry](http://straymindcough.blogspot.com/2015/01/hardware-accelerated-sha-1.html) about it, too.
Second, LLVM won't lower these intrinsics yet, so I started writing some functions to emulate the unusable intrinsics, and implemented SHA1 in terms of those emulated intrinsic functions, and it turned out to be quite fast! So I tried the same thing with SHA256 (which will have HW instructions at some point), and SHA512 (which I couldn't find any instruction designs for, so I made up my own).
I …
> Optimized SHA1 and SHA256

- src/lib.rs
- src/whirlpool.rs
I've implemented support for the Whirlpool hash algorithm. See <http://www.larc.usp.br/~pbarreto/WhirlpoolPage.html> and <https://en.wikipedia.org/wiki/Whirlpool_%28cryptography%29> for details.
My test values are taken from <http://www.larc.usp.br/%7Epbarreto/whirlpool.zip> and my implementation is based on the reference implementation - but it looks very different (the reference implementation itself is in the Public Domain). The algorithm has about 150 lines of rust code, the others are comments, tests and constants.
> Adds Whirlpool support

- src/curve25519.rs
- src/ed25519.rs
As may be known, key exchange and signing are only very slightly different operations on the same base curve. It is possible to convert Ed25519 keys to Curve25519 keys - but not vice versa (trivially, anyway), as far as I am aware. It is therefore possible to use a single keypair for both key exchange and signing, which cuts down on complexity. curve25519.rs is missing a keypair gen function (there is the curve25519_base function, but it lacks clamping), so this can stand in for that for the time being perhaps.
> Ed25519-keypair based key exchange/agreement

- src/aes.rs
8ff0ca2e0480042d2d32990bd2219701fa4ed702 only added the static lifetime bound to the x86/x86_64 variants
> Fixed aes.rs on non-x86 architectures

- src/cryptoutil.rs
- src/hc128.rs
- src/lib.rs
- src/sosemanuk.rs
Apologies, there was a error in my pull request for adding the SOSEMANUK cipher that didn't get caught due to the whole problem with the rust nightly binary. I thought I'd tested the latest test vectors that I added but it turns out I didn't, and there was a slight error (declared incorrect size for array that caused test to fail).
This new pull request is for adding the HC-128 stream cipher, and fixing the SOSEMANUK problem. I couldn't put it in two different pull requests (as I'd have liked to for tidiness), because they share a dependency on a u32-vector writing function that I added.
The SOSEMANUK cipher now writes its s-box output via this vector method, and is about 40 MB/s better for doing do.
The HC-128 cipher is amazingly fast.
Here's an output from cargo bench:
test …
> Add HC-128 cipher, and fix error in SOSEMANUK cipher test unit.

- Cargo.toml
- src/blake2b.rs
- src/blockmodes.rs
- src/blowfish.rs
- src/chacha20.rs
- src/cryptoutil.rs
- src/curve25519.rs
- src/fortuna.rs
- src/ghash.rs
- src/hc128.rs
- src/lib.rs
- src/md5.rs
- src/poly1305.rs
- src/rc4.rs
- src/ripemd160.rs
- src/salsa20.rs
- src/scrypt.rs
- src/sha1.rs
- src/sha2.rs
- src/simd.rs
- src/sosemanuk.rs
Fix problems resulting from Rust not checking for overflow / underflow:
* Work around a Rust bug with the overflow / underflow checking as it relates to SIMD types - rust-lang/rust#23037. When "ndebug" is NOT defined (ie: overflow checking is on), use a new "fake-SIMD" type that just simulates all of the SIMD operations using regular tuples of integer types. When "ndebug" is defined (ie: overflow checking is off), use the regular SIMD types.
* Replace all addition, subtraction, and multiplication that was causing test failures due to overflowing or underflowing with wrapped_add(), wrapped_sub(), or wrapped_mul() as appropriate.
* Disable optimizations for test builds to help try to make sure that no more overflowing or underflowing operations make it into the code base without using the …
> Fix problems resulting from Rust now checking for overflow / underflow

- Cargo.toml
- src/cryptoutil.rs
Makes rust-crypto compile on nightly once again.
> Make exported trait public

- src/bcrypt_pbkdf.rs
- src/blake2b.rs
- src/blockmodes.rs
- src/blowfish.rs
- src/curve25519.rs
- src/digest.rs
- src/ed25519.rs
- src/fortuna.rs
- src/ghash.rs
- src/hc128.rs
- src/hkdf.rs
- src/hmac.rs
- src/pbkdf2.rs
- src/poly1305.rs
- src/rc4.rs
- src/salsa20.rs
- src/scrypt.rs
- src/whirlpool.rs
This should fix the build for the latest nightly. Note that I didn't use the `x.as_mut_ref()` solution, but instead used `&mut x`. I believe this is the preferred way of denoting a slice.
The doc tests still fail on my machine. I couldn't get them to compile..
> Replace x.as_mut_ref() by &mut

- src/aes_gcm.rs
- src/aessafe.rs
- src/blake2b.rs
- src/blockmodes.rs
- src/buffer.rs
- src/cryptoutil.rs
- src/fortuna.rs
- src/ghash.rs
- src/hc128.rs
- src/hkdf.rs
- src/hmac.rs
- src/md5.rs
- src/pbkdf2.rs
- src/scrypt.rs
- src/sha1.rs
- src/sha2.rs
- src/sosemanuk.rs
This PR should fix breakages that will be caused by the next Rust nightly:
* The order of operands to some functions has been changed.
* The Int trait has been deprecated.
> Fixups for breaking Rust changes

- Cargo.toml
- build.rs
- src/aes.rs
- src/aes_gcm.rs
- src/aesni.rs
- src/aesni_helpers.c
- src/aessafe.rs
- src/bcrypt.rs
- src/bcrypt_pbkdf.rs
- src/blake2b.rs
- src/blockmodes.rs
- src/blowfish.rs
- src/buffer.rs
- src/cryptoutil.rs
- src/curve25519.rs
- src/ed25519.rs
- src/fortuna.rs
- src/ghash.rs
- src/hkdf.rs
- src/hmac.rs
- src/lib.rs
- src/md5.rs
- src/pbkdf2.rs
- src/scrypt.rs
- src/simd.rs
- src/sosemanuk.rs
- src/step_by.rs
- src/util.rs
- src/util_helpers.c
Remove all uses of unstable Rust features. This has two major impacts:
* SIMD types are disabled for now. I was hitting an ICE trying to conditionally enable them that I couldn't figure out how to get around. I think being usable with the beta is more important that a little bit of performance in the short term.
* I had to remove some assembly optimizations from Ghash since I couldn't figure out how to re-implement them in GCC assembly. The issue is that the Ghash code wants to pass the XMM registers by value, which Rust / LLVM seems to blow up on in the FFI. Hopefully we can figure out how to re-enable this.
* GCC is now required in order to build rust-crypto (although, it basically already was since its dependencies already used GCC to build).
This also bumps the version to v0.2.30.
> Remove all uses of unstable Rust features

- .travis.yml
Set 'sudo: false' in the .travis.yml file to take advantage of newer Travis build infrastructure
> Set 'sudo: false' in the .travis.yml file to take advantage of newer Travis build infrastructure

- .travis.yml
- src/curve25519.rs
- src/hc128.rs
Warnings output (Rust Compiler v1.3.0 @ Arch Linux):
```txt
Compiling gcc v0.3.18
Compiling rustc-serialize v0.3.16
Compiling winapi v0.2.4
Compiling winapi-build v0.1.1
Compiling libc v0.1.10
Compiling advapi32-sys v0.1.2
Compiling kernel32-sys v0.1.4
Compiling rand v0.3.11
Compiling time v0.1.32
Compiling rust-crypto v0.2.31 (file:///home/samet/projects/rust/rust-crypto)
src/curve25519.rs:338:13: 338:23 warning: variable does not need to be mutable, #[warn(unused_mut)] on by default
src/curve25519.rs:338         let mut carry1;
^~~~~~~~~~
src/curve25519.rs:339:13: 339:23 warning: variable does not need to be mutable, #[warn(unused_mut)] on by default
src/curve25519.rs:339         let mut carry2;
^~~~~~~~~~
src/curve25519.rs:340:13: 340:23 warning: variable does not need to be mutable, …
```
> Fix warnings at build time due to mutable objects.

- src/curve25519.rs
- src/hc128.rs
Now rust-crypto compiles without warnings.
> Fix 'variable does not need to be mutable'

- src/util_helpers.c
> Fix the ARM version of the rust_crypto_util_fixed_time_eq_asm() function

- src/aesni_helpers.c
- src/util_helpers.c
This fixes errors that GCC would report about the xmm registers not
being available for targets without SSE support.
Fixes #307
> Only attempt to compile the bodies of the AES-NI functions if SSE instructions are available

- build.rs
- src/aesni.rs
- src/aesni_helpers.asm
- src/util.rs
- src/util_helpers.asm
- src/util_helpers.c
Resolves issuing building with the MSVC based toolchain. The issue was that the build requires compiling some C files with inline assembly in the GCC format which is, unsurprisingly, not supported by MSVC. Additionally, MSVC doesn't support inline assembly at all on x86_64. So, the fixed time comparison and secure memory set routines have been ported to MASM assembly and the `build.rs` file has been updated to build those files instead of the C files with inline assembly used by GCC.
Significantly, the AES-NI implementation of AES is *not* ported. Any attempt to use that implementation will cause a `panic!()` which isn't a great solution, but its better than not compiling at all. Also, if using the functions in the `aes` module to dynamically pick the best AES implementation, it won't be …
> Implement assembly routines for MSVC based toolchains

- build.rs
gcc (at least, on OpenBSD, gcc 4.2.1 and gcc 4.9.3) are unable to build this library. Since that's the default compiler, it means that the build fails in rather obscure fashion.
> Use clang to build, unless the user explicitly specifies a different compiler

- src/bcrypt.rs
Previously, passing a cost of 31 would cause the shift operator to overflow, making it equivalent to `cost = 0`.  Fixes #332.
> bcrypt: Fix overflow when cost == 31.

- src/ed25519.rs
l is a core modulus of ed25519 and is therefore typically declared as a
global static variable. This also helps with performance, as keeping it
local to a stack frame could lead to a lot of useless copying.
> Make the l modulus a global static

- src/curve25519.rs
Its name doesn't accurately describe what it does, its functionality can
be implemented with a cast-and-shift, and it's only used once.
> Remove needless helper function negative()

- build.rs
When cross-compiling for msvc from a non-windows host, inline assembly is typically supported (for example via clang or clang-cl). Given that clang also doesn't support masm or have ml.exe compatibility, it's Most Unexceptional to use the C implementations of `util_helpers` and `aesni_helpers`.
> Use Inline assembly for msvc target from non-windows host

- build.rs
There have been reports that GCC doesn't compile Rust-Crypto on OpenBSD
while Clang works fine. However, on Linux platforms (at least Ubuntu
14.04+), GCC works fine and clang may not be installed. So, Only use
Clang by default on OpenBSD and continue to use GCC (as "cc")
everywhere else.
> Only use Clang on OpenBSD - default to cc (generally GCC) on other platforms

- Cargo.toml
This should probably carry a bump in the minor version of the library due to libc 0.1 to 0.2 incompatibilities when building.
> Upgraded libc to 0.2 branch

- build.rs
Current build script overrides target compiler and this cause problems with cross-compiling process. For example when our host is x86_64-unknown-linux-gnu and target arm-unknown-linux-gnueabi compilation will fail with following error:
```
failed to run custom build command for `rust-crypto v0.2.35`
Process didn't exit successfully: `/home/mk/git/box/server/target/release/build/rust-crypto-6acb19580f9fa57f/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("arm-unknown-linux-gnueabi")
OPT_LEVEL = Some("3")
PROFILE = Some("release")
TARGET = Some("arm-unknown-linux-gnueabi")
debug=false opt-level=3
TARGET = Some("arm-unknown-linux-gnueabi")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_arm-unknown-linux-gnueabi = None
CFLAGS_arm_unknown_linux_gnueabi = None
TARGET_CFLAGS = None …
```
> Fix cross compilation error

- src/blake2s.rs
- src/lib.rs
This tries to be as similar as possible to the blake2b implementation.
If you diff the two, you'll see just how little needed to be changed.
The test vectors come from the .txt in the reference implementation or
are generated with the reference implementation.
Fixes: #351
Signed-off-by: Jason A. Donenfeld <Jason@zx2c4.com>
> blake2s: add function

- appveyor.yml
Added Windows tests in Appveyor. Only targets that pass the tests have been added. That's all 4 targets for 1.8.0, but less for prior versions (i686 MSVC target wasn't working until 1.8.0 and no MSVC was working until 1.6.0, while in 1.4.0 not even the i686 GNU build was working).
You can see the results of the build here: https://ci.appveyor.com/project/Razican/rust-crypto/build/1.0.5
> Windows tests

- src/cryptoutil.rs
- src/md5.rs
- src/sha2.rs
- src/whirlpool.rs
This brings all hashing algorithms up to feature parity.
Closes #338
> Implement Copy and Clone for all Digest impls

- README.md
I noticed that sha3 is supported as of https://github.com/DaGenix/rust-crypto/pull/346, but not yet mentioned in the readme.
> Note that sha3 (keccak) is supported
